### PR TITLE
Fix uwp

### PR DESCRIPTION
**Pull request by ArtjomP**
This PR should fix the next issues: #32 #31 #21
Could @Aragas  release a beta NuGet package with the update? 
I would be glad to test it in production.

### CODE REVIEW

**Comment by Aragas** [comment]
@ArtjomP is everything going smooth?

**Comment by ArtjomP** [comment]
> @ArtjomP is everything going smooth?

Could you release a beta NuGet package? You just need to add -beta to the package version. I have a software where I reproduced the bug & can test eventually the updated package

**Comment by Aragas** [comment]
There already exists `PCLExt.FileStorage-devel` as a separate "nightly build" package, should it be the same package but with the beta pre-release postfix?

**Comment by ArtjomP** [comment]
Sorry, I didn't know about the [PCLExt.FileStorage-devel](https://www.nuget.org/packages/PCLExt.FileStorage-devel/) package. Does it include this PR? It doesn't look like the [devel branch](https://github.com/PCLExt/PCLExt.FileStorage/commits/devel) includes it as far as it was PR to the master.

**Comment by Aragas** [comment]
Oh, whoops! Could you redo the PR to devel too? I can trigger a master release manually I guess

**Comment by ArtjomP** [comment]
Ok let's make a PR to the devel branch

**Comment by ArtjomP** [comment]
done

**Comment by ArtjomP** [comment]
[PCLExt.FileStorage-devel -Version 1.5.0.319](https://www.nuget.org/packages/PCLExt.FileStorage-devel/1.5.0.319) works well for me

**Pull request merged**
